version: '3.3'

services:
  zentaris_apiserver:
    image: docker.io/zentaris/apiserver:v1.0.0
    container_name: zentaris_apiserver
    volumes:
      - certs:/etc/certs
    command: -httpsPort 8443 -cert /etc/certs/server.crt -key /etc/certs/server.key
    ports:
      - 8443:8443
    networks:
      - knetwork
    restart: unless-stopped

  zentaris_uiserver:
    image: docker.io/zentaris/uiserver:v1.0.0
    stdin_open: true
    container_name: zentaris_uiserver
    volumes:
      - certs:/etc/certs
    environment:
        - NODE_ENV=production
        - REACT_APP_SERVER=localhost:8443
        - HTTPS=true
        - PORT=3000
        - SSL_CRT_FILE=/etc/certs/server.crt
        - SSL_KEY_FILE=/etc/certs/server.key
    command: ["yarn", "start", "--verbose"]
    ports:
      - 3000:3000
    networks:
      - knetwork
    depends_on:
      - zentaris_apiserver
    restart: unless-stopped

volumes:
  certs:

networks:
  knetwork:
    driver: bridge
